parameters:
    article.entity.class: Bws\DoctrineBundle\Entity\Article
    article.repository.class: Bws\DoctrineBundle\Entity\ArticleRepository
    basket.entity.class: Bws\DoctrineBundle\Entity\Basket
    basket.repository.class: Bws\DoctrineBundle\Entity\BasketRepository
    basket.position.entity.class: Bws\DoctrineBundle\Entity\BasketPosition
    basket.position.repository.class: Bws\DoctrineBundle\Entity\BasketPositionRepository
    customer.entity.class: Bws\DoctrineBundle\Entity\Customer
    customer.repository.class: Bws\DoctrineBundle\Entity\CustomerRepository
    email.entity.class: Bws\DoctrineBundle\Entity\EmailAddress
    email.repository.class: Bws\DoctrineBundle\Entity\EmailAddressRepository
    invoiceaddress.entity.class: Bws\DoctrineBundle\Entity\InvoiceAddress
    invoiceaddress.repository.class: Bws\DoctrineBundle\Entity\InvoiceAddressRepository
    deliveryaddress.entity.class: Bws\DoctrineBundle\Entity\DeliveryAddress
    deliveryaddress.repository.class: Bws\DoctrineBundle\Entity\DeliveryAddressRepository
    logisticpartner.entity.class: Bws\DoctrineBundle\Entity\LogisticPartner
    logisticpartner.repository.class: Bws\DoctrineBundle\Entity\LogisticPartnerRepository
    order.entity.class: Bws\DoctrineBundle\Entity\Order
    order.repository.class: Bws\DoctrineBundle\Entity\OrderRepository
    paymentmethod.entity.class: Bws\DoctrineBundle\Entity\PaymentMethod
    paymentmethod.repository.class: Bws\DoctrineBundle\Entity\PaymentMethodRepository
